// <auto-generated />
using System;
using ConferenceRoomAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceRoomAPI.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRateSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "StartUtc", "EndUtc");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_HourlyRateSnapshot", "CAST(\"HourlyRateSnapshot\" AS NUMERIC) >= 0");

                            t.HasCheckConstraint("CK_Bookings_TimeRange", "\"EndUtc\" > \"StartUtc\"");

                            t.HasCheckConstraint("CK_Bookings_TotalPrice", "CAST(\"TotalPrice\" AS NUMERIC) >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.BookingExtraService", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId", "ExtraServiceId");

                    b.HasIndex("ExtraServiceId");

                    b.ToTable("BookingExtraServices", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingExtraServices_PriceSnapshot", "CAST(\"PriceSnapshot\" AS NUMERIC) >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExtraServices", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExtraServices_Price", "CAST(\"Price\" AS NUMERIC) >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_Capacity", "\"Capacity\" > 0");

                            t.HasCheckConstraint("CK_Rooms_HourlyRate", "CAST(\"HourlyRate\" AS NUMERIC) >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.RoomExtraService", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId", "ExtraServiceId");

                    b.HasIndex("ExtraServiceId");

                    b.ToTable("RoomExtraServices", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ConferenceRoomAPI.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.BookingExtraService", b =>
                {
                    b.HasOne("ConferenceRoomAPI.Domain.Entities.Booking", "Booking")
                        .WithMany("ExtraServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomAPI.Domain.Entities.ExtraService", "ExtraService")
                        .WithMany("Bookings")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ExtraService");
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.RoomExtraService", b =>
                {
                    b.HasOne("ConferenceRoomAPI.Domain.Entities.ExtraService", "ExtraService")
                        .WithMany("Rooms")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomAPI.Domain.Entities.Room", "Room")
                        .WithMany("ExtraServices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraService");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.Booking", b =>
                {
                    b.Navigation("ExtraServices");
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.ExtraService", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ConferenceRoomAPI.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ExtraServices");
                });
#pragma warning restore 612, 618
        }
    }
}
